on: [push, pull_request]

name: CI

jobs:
  CI:
    name: Node ${{ matrix.node }} and ${{ matrix.manager }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 24, 26]
        manager: ['npm', 'yarn', 'pnpm']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        if: ${{ matrix.manager == 'pnpm' }}
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies using ${{ matrix.manager }}
        run: ${{ matrix.manager }} install

      - name: Validate Prisma
        run: |
          if [ "${{ matrix.manager }}" == "pnpm" ]; then
            pnpm exec prisma generate && pnpm exec prisma validate
          elif [ "${{ matrix.manager }}" == "yarn" ]; then
            yarn prisma generate && yarn prisma validate
          else
            npx prisma generate && npx prisma validate
          fi

      - name: Run TypeScript type checking
        if: ${{ !startsWith(github.head_ref || github.ref_name, 'javascript') }}
        run: |
          if [ "${{ matrix.manager }}" == "pnpm" ]; then
            pnpm exec tsc --noEmit
          elif [ "${{ matrix.manager }}" == "yarn" ]; then
            yarn tsc --noEmit
          else
            npx tsc --noEmit
          fi

      - name: Run ESLint
        run: npm run lint

      - name: Build application
        run: npm run build
