name: Remove Waiting Labels
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
jobs:
  remove-labels-on-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Remove label
        if: contains(github.event.issue.labels.*.name, 'Waiting for Response')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue edit ${{ github.event.issue.number }} --repo ${{ github.repository }} --remove-label "Waiting for Response"
