name: Update JavaScript branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/convert-to-javascript.yml
    with:
      source-branch: main
      target-branch: javascript
